baseURL = 'https:/angelinagarae.dev/'
languageCode = 'fr'
title = 'data.gouv.nc'
theme = 'book'

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-XXXXXXXXX-X"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
disqusShortname = "my-site"

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy']

[params]
  BookTheme = 'light'
  BookToC = true
  BookLogo = 'logo.png'
  BookSection = '*'
  BookRepo = 'https://github.com/angelinagarae/docs_datagouvnc'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/'
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
  BookComments = true
  BookPortableLinks = true
  BookServiceWorker = true
  BookFavicon = "favicon.png"

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    title = "Guide de data.gouv.nc"
    languageCode = "fr"
    contentDir = "content/fr"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Guide of data.gouv.nc"
    languageCode = "en"
    contentDir = "content/en"

[menu]
  [[menu.main]]
    name = "Présentation"
    url = "/presentation/"
    weight = 1

  [[menu.main]]
    name = "Commencer"
    url = "/commencer/"
    weight = 2

  [[menu.main]]
    name = "Documentation"
    url = "/documentation/"
    weight = 3

  [[menu.main]]
    name = "Fonctionnalités"
    url = "/fonctionnalites/"
    weight = 4

  [[menu.main]]
    name = "Producteurs"
    url = "/producteurs/"
    weight = 5

  [[menu.main]]
    name = "Réutilisations"
    url = "/reutilisations/"
    weight = 6

  [[menu.main]]
    name = "APIs"
    url = "/apis/"
    weight = 7

  [[menu.main]]
    name = "Licence et droits"
    url = "/licence-et-droits/"
    weight = 8
